# -------------------------------------------------------------------------
# Welcome to Confiscate's main settings file
# -------------------------------------------------------------------------
#
# For material names, please use the following names:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
#
# For enchantments exceptions please use the names as specified per:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
#
# -------------------------------------------------------------------------

#
# Do not scan containers and inventories when the player has creative mode?
#
Ignore_Creative: true

#
# Remove items that might cause the server or the client to crash?
# This includes technical blocks like piston head, that cannot be used anyway.
#
Prevent_Crashable_Items: true

#
# Confiscated items are stored in a special room,
# so you can review them later.
#
# Please use '/c room set' to specify where the room should be!
Chest_Room: true

Scan: 
  #
  # Scan containers when the player opens them? 
  # Containers are chests, furnaces, enchant tables, etc.
  #
  Containers: 
    Enabled: true
    #
    # For names, see:
    # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/inventory/InventoryType.html
    #
    Exceptions: []
  
  #
  # Scan players' inventories when they log in or change worlds?
  # This is compatible with per world inventory plugins.
  #
  Inventories: true

Anti_Exploit: 
  Stacks: 
    #
    # Confiscate illegally stacked items (armor, minecart, boat etc.) ? 
    #
    Confiscate_Illegal: true
    Exceptions:
    - POTION
    
  #
  # For enchantments exceptions please use the names as specified per:
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
  #
  Enchants: 
    #
    # To respect custom items from other plugins, how much paranoid
    # the plugin should be to detect potentially modified items? 
    #
    # Level 0: Confiscate everything, nothing is ignored.
    # Level 1: Ignore if the item has lore or name with color codes.
    # Level 2: Ignore if the item has any lore, or name.
    #
    Allow_Modified_Strictness: 1
    #
    # Confiscate if the item has enchantment that cannot be given on enchantment table?
    # Due to enchant books it is recommended to leave this to false.
    #
    Confiscate_Non_Applicable: false
    #
    # Confiscate if the item has unnaturaly high enchantment level?
    #
    Confiscate_Too_High: true
    #
    # Remove enchants but retain the item for player? 
    # The item with all its illegal enchants will still be cloned into the chest roomn.
    #
    # CURRENTLY UNIMPLEMENTED
    #Supply_With_Unenchanted: true
    #
    # Allow the following enchants everywhere:
    #
    Exceptions_Non_Applicable: 
      - THORNS
    #
    # Allow the following enchants to exceed their natural max level to the specified maximum.
    #
    Exceptions_Too_High:
      SILK_TOUCH: 2

#
# For material names, please use the following names:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
#
Items: 
  #
  # Remove the following items completely? 
  # Usually those only obtainable via /give command can reveal abusive staff.
  #
  Confiscate:
    - SOIL
    - COMMAND
    - BARRIER
    - STRUCTURE_BLOCK
    - COMMAND_MINECART
  
  #
  # Remove the following items if player is not in creative mode when found?
  #
  Confiscate_Survival: 
    - BEDROCK
    - MONSTER_EGG
  
  #
  # Remove the following items if found above the limit?
  # Players having extreme high amount of these have usually obtained them
  # through server exploits or have been given them by abusive staff.
  #
  # Example: If the limit is 20x and you have 25x in your inventary/container, 
  #          the plugin will confiscate 5 pieces.
  #
  Confiscate_Above:  
    DIAMOND_BLOCK: 32
    DIAMOND: 128
    EMERALD_BLOCK: 32
    EMERALD: 128
    IRON_BLOCK: 150
    GOLD_BLOCK: 120
    REDSTONE_BLOCK: 250
    LAPIS_BLOCK: 320
    DRAGON_EGG: 5
    BEACON: 10
    
  #
  # Same as the section above, but only for newcomers.
  # New players usually don't dispose of high amount of luxury items,
  # so this might reveal abusive admins giving them items for free.
  #
  # You must have server statistics enabled in spigot.yml!
  #
  Confiscate_Newcomers:
    # 
    # How long is the player counted as newcomer?
    # Set to 'none' to disable.
    #
    # Example: If the threshold is 1 hour, all players that played on the
    #          server less then 1 hour are scanned.
    # 
    Threshold: 1 hour
    List:  
      DIAMOND_BLOCK: 3
      DIAMOND: 48
      EMERALD_BLOCK: 3
      EMERALD: 32
      IRON_BLOCK: 6
      GOLD_BLOCK: 6
      REDSTONE_BLOCK: 5
      LAPIS_BLOCK: 6
      DRAGON_EGG: 0
      BEACON: 0

# Allow debug to learn how the plugin works. It prints more messages to the console.
Debug: false

# Configuration version. Used to update your settings. Do not touch.
Version: 1